development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: reader_development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: reader_test

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: matt22
  socket: /tmp/mysql.sock
  database: reader_production